name: Generate release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create local.properties
        run: |
          echo "$LOCAL_PROPERTIES_BASE64" | base64 --decode > local.properties
          echo "storeFile=../keystore.jks" >> local.properties
        env:
          LOCAL_PROPERTIES_BASE64: ${{ secrets.LOCAL_PROPERTIES_BASE64 }}
      - name: Create keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Generate release APK
        run: ./gradlew assembleRelease --no-daemon
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk